//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.2.1
//
// Created by Quasar Development at 03-05-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

#import "FHBRequestResultHandler.h"
#import "DDXML.h"



@interface FHBad_type : NSObject 


@property (retain,nonatomic,getter=getName) NSString* name;

@property (retain,nonatomic,getter=getDesc) NSString* desc;

@property (retain,nonatomic,getter=getDesc_plural) NSString* desc_plural;

@property (retain,nonatomic,getter=getDesc_short) NSString* desc_short;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(FHBRequestResultHandler*) __request;
+(FHBad_type*) createWithXml:(DDXMLElement*)__node __request:(FHBRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(FHBRequestResultHandler*) __request;
@end