//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.2.1
//
// Created by Quasar Development at 03-05-2014
//
//---------------------------------------------------


#import "FHBHelper.h"
#import "FHBareas.h"


@implementation FHBareas
@synthesize api_key;
@synthesize area_type;
@synthesize ad_type;
@synthesize county;
@synthesize city;
@synthesize general;
@synthesize include_empty;

+ (FHBareas *)createWithXml:(DDXMLElement *)__node __request:(FHBRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.county =[NSMutableArray array];
        self.city =[NSMutableArray array];
        self.general =[NSMutableArray array];
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(FHBRequestResultHandler*) __request{
    if(self = [self init])
    {
        if([FHBHelper hasValue:__node name:@"api_key" index:0])
        {
            self.api_key = [[FHBHelper getNode:__node name:@"api_key" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"area_type" index:0])
        {
            self.area_type = [[FHBHelper getNode:__node name:@"area_type" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"ad_type" index:0])
        {
            self.ad_type = [[FHBHelper getNode:__node name:@"ad_type" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"county"])
        {
            NSArray* __items=[__node elementsForName:@"county"];
            for (DDXMLElement* __item in __items) {
                [self.county addObject:[FHBHelper getNumber:[__item stringValue]]];
            }
        }
        if([FHBHelper hasValue:__node name:@"city"])
        {
            NSArray* __items=[__node elementsForName:@"city"];
            for (DDXMLElement* __item in __items) {
                [self.city addObject:[FHBHelper getNumber:[__item stringValue]]];
            }
        }
        if([FHBHelper hasValue:__node name:@"general"])
        {
            NSArray* __items=[__node elementsForName:@"general"];
            for (DDXMLElement* __item in __items) {
                [self.general addObject:[FHBHelper getNumber:[__item stringValue]]];
            }
        }
        if([FHBHelper hasValue:__node name:@"include_empty" index:0])
        {
            self.include_empty = [[NSNumber alloc]initWithBool:[[[FHBHelper getNode:__node name:@"include_empty" index:0] stringValue] boolValue]];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(FHBRequestResultHandler*) __request
{

             
        DDXMLElement* __api_keyItemElement=[__request writeElement:api_key type:[NSString class] name:@"api_key" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__api_keyItemElement!=nil)
        {
            [__api_keyItemElement setStringValue:self.api_key];
        }
             
        DDXMLElement* __area_typeItemElement=[__request writeElement:area_type type:[NSString class] name:@"area_type" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__area_typeItemElement!=nil)
        {
            [__area_typeItemElement setStringValue:self.area_type];
        }
             
        DDXMLElement* __ad_typeItemElement=[__request writeElement:ad_type type:[NSString class] name:@"ad_type" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ad_typeItemElement!=nil)
        {
            [__ad_typeItemElement setStringValue:self.ad_type];
        }
             
        if(self.county!=nil)
        {
            for (NSNumber* __item in self.county) {
                DDXMLElement* __countyItemElement=[__request writeElement:county type:[NSNumber class] name:@"county" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:NO];
                if(__countyItemElement!=nil)
                {
                    [__countyItemElement setStringValue:[__item stringValue]];
                }
            }
        }
             
        if(self.city!=nil)
        {
            for (NSNumber* __item in self.city) {
                DDXMLElement* __cityItemElement=[__request writeElement:city type:[NSNumber class] name:@"city" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:NO];
                if(__cityItemElement!=nil)
                {
                    [__cityItemElement setStringValue:[__item stringValue]];
                }
            }
        }
             
        if(self.general!=nil)
        {
            for (NSNumber* __item in self.general) {
                DDXMLElement* __generalItemElement=[__request writeElement:general type:[NSNumber class] name:@"general" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:NO];
                if(__generalItemElement!=nil)
                {
                    [__generalItemElement setStringValue:[__item stringValue]];
                }
            }
        }
             
        DDXMLElement* __include_emptyItemElement=[__request writeElement:include_empty type:[NSNumber class] name:@"include_empty" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__include_emptyItemElement!=nil)
        {
            [__include_emptyItemElement setStringValue:[FHBHelper toBoolStringFromNumber:self.include_empty]];
        }


}
@end
