//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.2.1
//
// Created by Quasar Development at 03-05-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class FHBHelper;
#import "FHBRequestResultHandler.h"
#import "DDXML.h"



@interface FHBarea : NSObject 


@property (retain,nonatomic,getter=get_id) NSNumber* _id;

@property (retain,nonatomic,getter=getName) NSString* name;

@property (retain,nonatomic,getter=getProperties) NSNumber* properties;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(FHBRequestResultHandler*) __request;
+(FHBarea*) createWithXml:(DDXMLElement*)__node __request:(FHBRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(FHBRequestResultHandler*) __request;
@end