//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.2.1
//
// Created by Quasar Development at 03-05-2014
//
//---------------------------------------------------


#import "FHBHelper.h"
#import "FHBarea.h"


@implementation FHBarea
@synthesize _id;
@synthesize name;
@synthesize properties;

+ (FHBarea *)createWithXml:(DDXMLElement *)__node __request:(FHBRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self._id =[NSNumber numberWithInt:0];
        self.properties =[NSNumber numberWithInt:0];
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(FHBRequestResultHandler*) __request{
    if(self = [self init])
    {
        if([FHBHelper hasValue:__node name:@"id" index:0])
        {
            self._id = [FHBHelper getNumber:[[FHBHelper getNode:__node name:@"id" index:0] stringValue]];
        }
        if([FHBHelper hasValue:__node name:@"name" index:0])
        {
            self.name = [[FHBHelper getNode:__node name:@"name" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"properties" index:0])
        {
            self.properties = [FHBHelper getNumber:[[FHBHelper getNode:__node name:@"properties" index:0] stringValue]];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(FHBRequestResultHandler*) __request
{

             
        DDXMLElement* ___idItemElement=[__request writeElement:_id type:[NSNumber class] name:@"id" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(___idItemElement!=nil)
        {
            [___idItemElement setStringValue:[self._id stringValue]];
        }
             
        DDXMLElement* __nameItemElement=[__request writeElement:name type:[NSString class] name:@"name" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__nameItemElement!=nil)
        {
            [__nameItemElement setStringValue:self.name];
        }
             
        DDXMLElement* __propertiesItemElement=[__request writeElement:properties type:[NSNumber class] name:@"properties" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__propertiesItemElement!=nil)
        {
            [__propertiesItemElement setStringValue:[self.properties stringValue]];
        }


}
@end
