//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.2.1
//
// Created by Quasar Development at 03-05-2014
//
//---------------------------------------------------


#import "FHBHelper.h"
#import "FHBdocument.h"


@implementation FHBdocument
@synthesize caption;
@synthesize url;

+ (FHBdocument *)createWithXml:(DDXMLElement *)__node __request:(FHBRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(FHBRequestResultHandler*) __request{
    if(self = [self init])
    {
        if([FHBHelper hasValue:__node name:@"caption" index:0])
        {
            self.caption = [[FHBHelper getNode:__node name:@"caption" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"url" index:0])
        {
            self.url = [[FHBHelper getNode:__node name:@"url" index:0] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(FHBRequestResultHandler*) __request
{

             
        DDXMLElement* __captionItemElement=[__request writeElement:caption type:[NSString class] name:@"caption" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__captionItemElement!=nil)
        {
            [__captionItemElement setStringValue:self.caption];
        }
             
        DDXMLElement* __urlItemElement=[__request writeElement:url type:[NSString class] name:@"url" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__urlItemElement!=nil)
        {
            [__urlItemElement setStringValue:self.url];
        }


}
@end
