//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.2.1
//
// Created by Quasar Development at 03-05-2014
//
//---------------------------------------------------


#import "FHBDaftAPIServiceBinding.h"
#import "FHBRequestResultHandler.h"
#import "FHBHelper.h"

@implementation FHBDaftAPIServiceBinding
@synthesize Url,ShouldAddAdornments,Headers;

- (id) init {
    if(self = [super init])
    {
        self.Url=@"http://api.daft.ie/v2/";
        self.ShouldAddAdornments=YES;
    }
    return self;
}

- (id) initWithUrl: (NSString*) url {
    if(self = [self init])
    {
        self.Url=url;
    }
    return self;
}

-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(FHBRequestResultHandler*) requestMgr
{
    [requestMgr sendImplementation:request];
}

-(FHBRequestResultHandler*) CreateRequestResultHandler
{
    return [[FHBRequestResultHandler alloc]init];
}
-(NSMutableURLRequest*) createRequest:(NSString *)__soapAction __request:(FHBRequestResultHandler*) __request
{
    NSString *__soapMessage=[__request getEnvelopeString];
    NSURL *__url = [NSURL URLWithString:Url];
    NSMutableURLRequest *__requestObj = [NSMutableURLRequest requestWithURL:__url];
    NSString *msgLength = [NSString stringWithFormat:@"%d", [__soapMessage length]];

    [__requestObj addValue: @"text/xml; charset=utf-8" forHTTPHeaderField:@"Content-Type"];
    [__requestObj addValue: __soapAction forHTTPHeaderField:@"SOAPAction"];
    [__requestObj addValue: msgLength forHTTPHeaderField:@"Content-Length"];
    for (NSString* key in self.Headers) {
        [__requestObj addValue: [self.Headers objectForKey:key] forHTTPHeaderField:key];
    }
    [__requestObj setHTTPMethod:@"POST"];
    [__requestObj setHTTPBody: [__soapMessage dataUsingEncoding:NSUTF8StringEncoding]];
    return __requestObj;
}

-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(FHBRequestResultHandler*) requestMgr callback:(void (^)(FHBRequestResultHandler *)) callback
{
    [requestMgr sendImplementation:request callbackDelegate:callback];
}

-(void) addAdornments:(DDXMLElement*)__methodElement
{
    if(ShouldAddAdornments)
    {
        [__methodElement addAttribute:[DDXMLNode attributeWithName:@"id" stringValue:@"o0"]];
        [__methodElement addAttribute:[DDXMLNode attributeWithName:@"c:root" stringValue:@"1"]];
    }
}

-(NSMutableURLRequest*) createtestRequest:(NSString*) api_key __request:(FHBRequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"test" URI:@"http://api.daft.ie/v2/" parent:__request.Body];
    [self addAdornments:__methodElement];
             
        DDXMLElement* __api_keyItemElement=[__request writeElement:api_key type:[NSString class] name:@"api_key" URI:@"http://api.daft.ie/v2/" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__api_keyItemElement!=nil)
        {
            [__api_keyItemElement setStringValue:api_key];
        }
    
    NSMutableURLRequest* __requestObj= [self createRequest:@"DaftAPIService#test"  __request:__request];
    return __requestObj;
}

-(FHBRequestResultHandler*) testAsync:(NSString*) api_key __target:(id) __target __handler:(SEL) __handler
{
    FHBRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createtestRequest:api_key __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(FHBRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[FHBHelper getResultElement:__request.OutputBody name:@"status"];
        __res= [__result stringValue];
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    IMP imp = [__target methodForSelector:__handler];
    void (*func)(id, SEL,id) = (void *)imp;
    func(__target, __handler,__res);
    }];
    return __request;
}

-(FHBRequestResultHandler*) testAsync:(NSString*) api_key __target:(id<FHBSoapServiceResponse>) __target
{
    FHBRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createtestRequest:api_key __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(FHBRequestResultHandler *__requestMgr) {
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[FHBHelper getResultElement:__request.OutputBody name:@"status"];
        [__target onSuccess:[__result stringValue]];
    }
    else
    {
        [__target onError:__requestMgr.OutputFault];
    }
    }];
    return __request;
}

-(NSString*) test:(NSString*) api_key __error:(NSError**) __error 
{
    FHBRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createtestRequest:api_key __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[FHBHelper getResultElement:__request.OutputBody name:@"status"];
    return [__result stringValue];
}
-(NSMutableURLRequest*) createad_typesRequest:(NSString*) api_key __request:(FHBRequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"ad_types" URI:@"http://api.daft.ie/v2/" parent:__request.Body];
    [self addAdornments:__methodElement];
             
        DDXMLElement* __api_keyItemElement=[__request writeElement:api_key type:[NSString class] name:@"api_key" URI:@"http://api.daft.ie/v2/" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__api_keyItemElement!=nil)
        {
            [__api_keyItemElement setStringValue:api_key];
        }
    
    NSMutableURLRequest* __requestObj= [self createRequest:@"DaftAPIService#ad_types"  __request:__request];
    return __requestObj;
}

-(FHBRequestResultHandler*) ad_typesAsync:(NSString*) api_key __target:(id) __target __handler:(SEL) __handler
{
    FHBRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createad_typesRequest:api_key __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(FHBRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[FHBHelper getResultElement:__request.OutputBody name:@"ad_typesResponse"];
        __res= (FHBad_typesResponse*)[__request createObject:__result type:[FHBad_typesResponse class]];
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    IMP imp = [__target methodForSelector:__handler];
    void (*func)(id, SEL,id) = (void *)imp;
    func(__target, __handler,__res);
    }];
    return __request;
}

-(FHBRequestResultHandler*) ad_typesAsync:(NSString*) api_key __target:(id<FHBSoapServiceResponse>) __target
{
    FHBRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createad_typesRequest:api_key __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(FHBRequestResultHandler *__requestMgr) {
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[FHBHelper getResultElement:__request.OutputBody name:@"ad_typesResponse"];
        [__target onSuccess:(FHBad_typesResponse*)[__request createObject:__result type:[FHBad_typesResponse class]]];
    }
    else
    {
        [__target onError:__requestMgr.OutputFault];
    }
    }];
    return __request;
}

-(FHBad_typesResponse*) ad_types:(NSString*) api_key __error:(NSError**) __error 
{
    FHBRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createad_typesRequest:api_key __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[FHBHelper getResultElement:__request.OutputBody name:@"ad_typesResponse"];
    return (FHBad_typesResponse*)[__request createObject:__result type:[FHBad_typesResponse class]];
}
-(NSMutableURLRequest*) createfeaturesRequest:(NSString*) api_key ad_type:(NSString*) ad_type __request:(FHBRequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"features" URI:@"http://api.daft.ie/v2/" parent:__request.Body];
    [self addAdornments:__methodElement];
             
        DDXMLElement* __api_keyItemElement=[__request writeElement:api_key type:[NSString class] name:@"api_key" URI:@"http://api.daft.ie/v2/" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__api_keyItemElement!=nil)
        {
            [__api_keyItemElement setStringValue:api_key];
        }
             
        DDXMLElement* __ad_typeItemElement=[__request writeElement:ad_type type:[NSString class] name:@"ad_type" URI:@"http://api.daft.ie/v2/" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__ad_typeItemElement!=nil)
        {
            [__ad_typeItemElement setStringValue:ad_type];
        }
    
    NSMutableURLRequest* __requestObj= [self createRequest:@"DaftAPIService#features"  __request:__request];
    return __requestObj;
}

-(FHBRequestResultHandler*) featuresAsync:(NSString*) api_key ad_type:(NSString*) ad_type __target:(id) __target __handler:(SEL) __handler
{
    FHBRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createfeaturesRequest:api_key ad_type: ad_type __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(FHBRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[FHBHelper getResultElement:__request.OutputBody name:@"featuresResponse"];
        __res= (FHBfeaturesResponse*)[__request createObject:__result type:[FHBfeaturesResponse class]];
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    IMP imp = [__target methodForSelector:__handler];
    void (*func)(id, SEL,id) = (void *)imp;
    func(__target, __handler,__res);
    }];
    return __request;
}

-(FHBRequestResultHandler*) featuresAsync:(NSString*) api_key ad_type:(NSString*) ad_type __target:(id<FHBSoapServiceResponse>) __target
{
    FHBRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createfeaturesRequest:api_key ad_type: ad_type __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(FHBRequestResultHandler *__requestMgr) {
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[FHBHelper getResultElement:__request.OutputBody name:@"featuresResponse"];
        [__target onSuccess:(FHBfeaturesResponse*)[__request createObject:__result type:[FHBfeaturesResponse class]]];
    }
    else
    {
        [__target onError:__requestMgr.OutputFault];
    }
    }];
    return __request;
}

-(FHBfeaturesResponse*) features:(NSString*) api_key ad_type:(NSString*) ad_type __error:(NSError**) __error 
{
    FHBRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createfeaturesRequest:api_key ad_type: ad_type __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[FHBHelper getResultElement:__request.OutputBody name:@"featuresResponse"];
    return (FHBfeaturesResponse*)[__request createObject:__result type:[FHBfeaturesResponse class]];
}
-(NSMutableURLRequest*) createproperty_typesRequest:(NSString*) api_key ad_type:(NSString*) ad_type __request:(FHBRequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"property_types" URI:@"http://api.daft.ie/v2/" parent:__request.Body];
    [self addAdornments:__methodElement];
             
        DDXMLElement* __api_keyItemElement=[__request writeElement:api_key type:[NSString class] name:@"api_key" URI:@"http://api.daft.ie/v2/" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__api_keyItemElement!=nil)
        {
            [__api_keyItemElement setStringValue:api_key];
        }
             
        DDXMLElement* __ad_typeItemElement=[__request writeElement:ad_type type:[NSString class] name:@"ad_type" URI:@"http://api.daft.ie/v2/" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__ad_typeItemElement!=nil)
        {
            [__ad_typeItemElement setStringValue:ad_type];
        }
    
    NSMutableURLRequest* __requestObj= [self createRequest:@"DaftAPIService#property_types"  __request:__request];
    return __requestObj;
}

-(FHBRequestResultHandler*) property_typesAsync:(NSString*) api_key ad_type:(NSString*) ad_type __target:(id) __target __handler:(SEL) __handler
{
    FHBRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createproperty_typesRequest:api_key ad_type: ad_type __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(FHBRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[FHBHelper getResultElement:__request.OutputBody name:@"property_typesResponse"];
        __res= (FHBproperty_typesResponse*)[__request createObject:__result type:[FHBproperty_typesResponse class]];
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    IMP imp = [__target methodForSelector:__handler];
    void (*func)(id, SEL,id) = (void *)imp;
    func(__target, __handler,__res);
    }];
    return __request;
}

-(FHBRequestResultHandler*) property_typesAsync:(NSString*) api_key ad_type:(NSString*) ad_type __target:(id<FHBSoapServiceResponse>) __target
{
    FHBRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createproperty_typesRequest:api_key ad_type: ad_type __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(FHBRequestResultHandler *__requestMgr) {
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[FHBHelper getResultElement:__request.OutputBody name:@"property_typesResponse"];
        [__target onSuccess:(FHBproperty_typesResponse*)[__request createObject:__result type:[FHBproperty_typesResponse class]]];
    }
    else
    {
        [__target onError:__requestMgr.OutputFault];
    }
    }];
    return __request;
}

-(FHBproperty_typesResponse*) property_types:(NSString*) api_key ad_type:(NSString*) ad_type __error:(NSError**) __error 
{
    FHBRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createproperty_typesRequest:api_key ad_type: ad_type __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[FHBHelper getResultElement:__request.OutputBody name:@"property_typesResponse"];
    return (FHBproperty_typesResponse*)[__request createObject:__result type:[FHBproperty_typesResponse class]];
}
-(NSMutableURLRequest*) createareasRequest:(FHBareas*) areas __request:(FHBRequestResultHandler*) __request
{
    DDXMLElement *__methodElement=__request.Body;
    [self addAdornments:__methodElement];
             
        DDXMLElement* __areasItemElement=[__request writeElement:areas type:[FHBareas class] name:@"areas" URI:@"http://api.daft.ie/v2/" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__areasItemElement!=nil)
        {
            [areas serialize:__areasItemElement __request: __request];
        }
    
    NSMutableURLRequest* __requestObj= [self createRequest:@"DaftAPIService#areas"  __request:__request];
    return __requestObj;
}

-(FHBRequestResultHandler*) areasAsync:(FHBareas*) areas __target:(id) __target __handler:(SEL) __handler
{
    FHBRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createareasRequest:areas __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(FHBRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__mainReturn=(DDXMLElement*)[__request.OutputBody childAtIndex:0];
        __res= (FHBareasResponse*)[__request createObject:__mainReturn type:[FHBareasResponse class]];
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    IMP imp = [__target methodForSelector:__handler];
    void (*func)(id, SEL,id) = (void *)imp;
    func(__target, __handler,__res);
    }];
    return __request;
}

-(FHBRequestResultHandler*) areasAsync:(FHBareas*) areas __target:(id<FHBSoapServiceResponse>) __target
{
    FHBRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createareasRequest:areas __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(FHBRequestResultHandler *__requestMgr) {
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__mainReturn=(DDXMLElement*)[__request.OutputBody childAtIndex:0];
        [__target onSuccess:(FHBareasResponse*)[__request createObject:__mainReturn type:[FHBareasResponse class]]];
    }
    else
    {
        [__target onError:__requestMgr.OutputFault];
    }
    }];
    return __request;
}

-(FHBareasResponse*) areas:(FHBareas*) areas __error:(NSError**) __error 
{
    FHBRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createareasRequest:areas __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__mainReturn=(DDXMLElement*)[__request.OutputBody childAtIndex:0];
    return (FHBareasResponse*)[__request createObject:__mainReturn type:[FHBareasResponse class]];
}
-(NSMutableURLRequest*) createmediaRequest:(NSString*) api_key ad_type:(NSString*) ad_type ad_id:(NSNumber*) ad_id __request:(FHBRequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"media" URI:@"http://api.daft.ie/v2/" parent:__request.Body];
    [self addAdornments:__methodElement];
             
        DDXMLElement* __api_keyItemElement=[__request writeElement:api_key type:[NSString class] name:@"api_key" URI:@"http://api.daft.ie/v2/" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__api_keyItemElement!=nil)
        {
            [__api_keyItemElement setStringValue:api_key];
        }
             
        DDXMLElement* __ad_typeItemElement=[__request writeElement:ad_type type:[NSString class] name:@"ad_type" URI:@"http://api.daft.ie/v2/" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__ad_typeItemElement!=nil)
        {
            [__ad_typeItemElement setStringValue:ad_type];
        }
             
        DDXMLElement* __ad_idItemElement=[__request writeElement:ad_id type:[NSNumber class] name:@"ad_id" URI:@"http://api.daft.ie/v2/" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__ad_idItemElement!=nil)
        {
            [__ad_idItemElement setStringValue:[ad_id stringValue]];
        }
    
    NSMutableURLRequest* __requestObj= [self createRequest:@"DaftAPIService#media"  __request:__request];
    return __requestObj;
}

-(FHBRequestResultHandler*) mediaAsync:(NSString*) api_key ad_type:(NSString*) ad_type ad_id:(NSNumber*) ad_id __target:(id) __target __handler:(SEL) __handler
{
    FHBRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createmediaRequest:api_key ad_type: ad_type ad_id: ad_id __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(FHBRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[FHBHelper getResultElement:__request.OutputBody name:@"media"];
        __res= (FHBmedia*)[__request createObject:__result type:[FHBmedia class]];
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    IMP imp = [__target methodForSelector:__handler];
    void (*func)(id, SEL,id) = (void *)imp;
    func(__target, __handler,__res);
    }];
    return __request;
}

-(FHBRequestResultHandler*) mediaAsync:(NSString*) api_key ad_type:(NSString*) ad_type ad_id:(NSNumber*) ad_id __target:(id<FHBSoapServiceResponse>) __target
{
    FHBRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createmediaRequest:api_key ad_type: ad_type ad_id: ad_id __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(FHBRequestResultHandler *__requestMgr) {
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[FHBHelper getResultElement:__request.OutputBody name:@"media"];
        [__target onSuccess:(FHBmedia*)[__request createObject:__result type:[FHBmedia class]]];
    }
    else
    {
        [__target onError:__requestMgr.OutputFault];
    }
    }];
    return __request;
}

-(FHBmedia*) media:(NSString*) api_key ad_type:(NSString*) ad_type ad_id:(NSNumber*) ad_id __error:(NSError**) __error 
{
    FHBRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createmediaRequest:api_key ad_type: ad_type ad_id: ad_id __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[FHBHelper getResultElement:__request.OutputBody name:@"media"];
    return (FHBmedia*)[__request createObject:__result type:[FHBmedia class]];
}
-(NSMutableURLRequest*) createsearch_saleRequest:(NSString*) api_key query:(FHBsearch_query*) query __request:(FHBRequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"search_sale" URI:@"http://api.daft.ie/v2/" parent:__request.Body];
    [self addAdornments:__methodElement];
             
        DDXMLElement* __api_keyItemElement=[__request writeElement:api_key type:[NSString class] name:@"api_key" URI:@"http://api.daft.ie/v2/" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__api_keyItemElement!=nil)
        {
            [__api_keyItemElement setStringValue:api_key];
        }
             
        DDXMLElement* __queryItemElement=[__request writeElement:query type:[FHBsearch_query class] name:@"query" URI:@"http://api.daft.ie/v2/" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__queryItemElement!=nil)
        {
            [query serialize:__queryItemElement __request: __request];
        }
    
    NSMutableURLRequest* __requestObj= [self createRequest:@"DaftAPIService#search_sale"  __request:__request];
    return __requestObj;
}

-(FHBRequestResultHandler*) search_saleAsync:(NSString*) api_key query:(FHBsearch_query*) query __target:(id) __target __handler:(SEL) __handler
{
    FHBRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createsearch_saleRequest:api_key query: query __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(FHBRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[FHBHelper getResultElement:__request.OutputBody name:@"results"];
        __res= (FHBsale_results*)[__request createObject:__result type:[FHBsale_results class]];
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    IMP imp = [__target methodForSelector:__handler];
    void (*func)(id, SEL,id) = (void *)imp;
    func(__target, __handler,__res);
    }];
    return __request;
}

-(FHBRequestResultHandler*) search_saleAsync:(NSString*) api_key query:(FHBsearch_query*) query __target:(id<FHBSoapServiceResponse>) __target
{
    FHBRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createsearch_saleRequest:api_key query: query __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(FHBRequestResultHandler *__requestMgr) {
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[FHBHelper getResultElement:__request.OutputBody name:@"results"];
        [__target onSuccess:(FHBsale_results*)[__request createObject:__result type:[FHBsale_results class]]];
    }
    else
    {
        [__target onError:__requestMgr.OutputFault];
    }
    }];
    return __request;
}

-(FHBsale_results*) search_sale:(NSString*) api_key query:(FHBsearch_query*) query __error:(NSError**) __error 
{
    FHBRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createsearch_saleRequest:api_key query: query __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[FHBHelper getResultElement:__request.OutputBody name:@"results"];
    return (FHBsale_results*)[__request createObject:__result type:[FHBsale_results class]];
}

-(FHBRequestResultHandler*) search_rentalAsync:(NSString*) api_key query:(NSString*) query __target:(id) __target __handler:(SEL) __handler
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

-(FHBRequestResultHandler*) search_rentalAsync:(NSString*) api_key query:(NSString*) query __target:(id<FHBSoapServiceResponse>) __target
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

-(NSString*) search_rental:(NSString*) api_key query:(NSString*) query __error:(NSError**) __error 
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

-(FHBRequestResultHandler*) search_commercialAsync:(NSString*) api_key query:(NSString*) query __target:(id) __target __handler:(SEL) __handler
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

-(FHBRequestResultHandler*) search_commercialAsync:(NSString*) api_key query:(NSString*) query __target:(id<FHBSoapServiceResponse>) __target
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

-(NSString*) search_commercial:(NSString*) api_key query:(NSString*) query __error:(NSError**) __error 
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

-(FHBRequestResultHandler*) search_new_developmentAsync:(NSString*) api_key query:(NSString*) query __target:(id) __target __handler:(SEL) __handler
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

-(FHBRequestResultHandler*) search_new_developmentAsync:(NSString*) api_key query:(NSString*) query __target:(id<FHBSoapServiceResponse>) __target
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

-(NSString*) search_new_development:(NSString*) api_key query:(NSString*) query __error:(NSError**) __error 
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

-(FHBRequestResultHandler*) search_shorttermAsync:(NSString*) api_key query:(NSString*) query __target:(id) __target __handler:(SEL) __handler
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

-(FHBRequestResultHandler*) search_shorttermAsync:(NSString*) api_key query:(NSString*) query __target:(id<FHBSoapServiceResponse>) __target
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

-(NSString*) search_shortterm:(NSString*) api_key query:(NSString*) query __error:(NSError**) __error 
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

-(FHBRequestResultHandler*) search_sharingAsync:(NSString*) api_key query:(NSString*) query __target:(id) __target __handler:(SEL) __handler
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

-(FHBRequestResultHandler*) search_sharingAsync:(NSString*) api_key query:(NSString*) query __target:(id<FHBSoapServiceResponse>) __target
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

-(NSString*) search_sharing:(NSString*) api_key query:(NSString*) query __error:(NSError**) __error 
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

-(FHBRequestResultHandler*) search_parkingAsync:(NSString*) api_key query:(NSString*) query __target:(id) __target __handler:(SEL) __handler
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

-(FHBRequestResultHandler*) search_parkingAsync:(NSString*) api_key query:(NSString*) query __target:(id<FHBSoapServiceResponse>) __target
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

-(NSString*) search_parking:(NSString*) api_key query:(NSString*) query __error:(NSError**) __error 
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

-(FHBRequestResultHandler*) agent_infoAsync:(NSString*) api_key ad_id:(NSString*) ad_id ad_type:(NSString*) ad_type __target:(id) __target __handler:(SEL) __handler
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

-(FHBRequestResultHandler*) agent_infoAsync:(NSString*) api_key ad_id:(NSString*) ad_id ad_type:(NSString*) ad_type __target:(id<FHBSoapServiceResponse>) __target
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

-(NSString*) agent_info:(NSString*) api_key ad_id:(NSString*) ad_id ad_type:(NSString*) ad_type __error:(NSError**) __error 
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

@end
