//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.2.1
//
// Created by Quasar Development at 03-05-2014
//
//---------------------------------------------------



#import <Foundation/Foundation.h>

#import "FHBad_typesResponse.h"
#import "FHBfeaturesResponse.h"
#import "FHBproperty_typesResponse.h"
#import "FHBareasResponse.h"
#import "FHBareas.h"
#import "FHBmedia.h"
#import "FHBHelper.h"
#import "FHBsale_results.h"
#import "FHBsearch_query.h"
#import "DDXML.h"

@class FHBRequestResultHandler;

@protocol FHBSoapServiceResponse < NSObject>
- (void) onSuccess: (id) value;
- (void) onError: (NSError*) error;
@end


@interface FHBDaftAPIServiceBinding : NSObject
    
@property (retain, nonatomic) NSDictionary* Headers;
@property (retain, nonatomic) NSString* Url;
@property (nonatomic) BOOL ShouldAddAdornments;

- (id) init;
- (id) initWithUrl: (NSString*) url;

-(NSMutableURLRequest*) createtestRequest:(NSString*) api_key __request:(FHBRequestResultHandler*) __request;
-(NSString*) test:(NSString*) api_key __error:(NSError**) __error;
-(FHBRequestResultHandler*) testAsync:(NSString*) api_key __target:(id) __target __handler:(SEL) __handler;
-(FHBRequestResultHandler*) testAsync:(NSString*) api_key __target:(id<FHBSoapServiceResponse>) __target;
-(NSMutableURLRequest*) createad_typesRequest:(NSString*) api_key __request:(FHBRequestResultHandler*) __request;
-(FHBad_typesResponse*) ad_types:(NSString*) api_key __error:(NSError**) __error;
-(FHBRequestResultHandler*) ad_typesAsync:(NSString*) api_key __target:(id) __target __handler:(SEL) __handler;
-(FHBRequestResultHandler*) ad_typesAsync:(NSString*) api_key __target:(id<FHBSoapServiceResponse>) __target;
-(NSMutableURLRequest*) createfeaturesRequest:(NSString*) api_key ad_type:(NSString*) ad_type __request:(FHBRequestResultHandler*) __request;
-(FHBfeaturesResponse*) features:(NSString*) api_key ad_type:(NSString*) ad_type __error:(NSError**) __error;
-(FHBRequestResultHandler*) featuresAsync:(NSString*) api_key ad_type:(NSString*) ad_type __target:(id) __target __handler:(SEL) __handler;
-(FHBRequestResultHandler*) featuresAsync:(NSString*) api_key ad_type:(NSString*) ad_type __target:(id<FHBSoapServiceResponse>) __target;
-(NSMutableURLRequest*) createproperty_typesRequest:(NSString*) api_key ad_type:(NSString*) ad_type __request:(FHBRequestResultHandler*) __request;
-(FHBproperty_typesResponse*) property_types:(NSString*) api_key ad_type:(NSString*) ad_type __error:(NSError**) __error;
-(FHBRequestResultHandler*) property_typesAsync:(NSString*) api_key ad_type:(NSString*) ad_type __target:(id) __target __handler:(SEL) __handler;
-(FHBRequestResultHandler*) property_typesAsync:(NSString*) api_key ad_type:(NSString*) ad_type __target:(id<FHBSoapServiceResponse>) __target;
-(NSMutableURLRequest*) createareasRequest:(FHBareas*) areas __request:(FHBRequestResultHandler*) __request;
-(FHBareasResponse*) areas:(FHBareas*) areas __error:(NSError**) __error;
-(FHBRequestResultHandler*) areasAsync:(FHBareas*) areas __target:(id) __target __handler:(SEL) __handler;
-(FHBRequestResultHandler*) areasAsync:(FHBareas*) areas __target:(id<FHBSoapServiceResponse>) __target;
-(NSMutableURLRequest*) createmediaRequest:(NSString*) api_key ad_type:(NSString*) ad_type ad_id:(NSNumber*) ad_id __request:(FHBRequestResultHandler*) __request;
-(FHBmedia*) media:(NSString*) api_key ad_type:(NSString*) ad_type ad_id:(NSNumber*) ad_id __error:(NSError**) __error;
-(FHBRequestResultHandler*) mediaAsync:(NSString*) api_key ad_type:(NSString*) ad_type ad_id:(NSNumber*) ad_id __target:(id) __target __handler:(SEL) __handler;
-(FHBRequestResultHandler*) mediaAsync:(NSString*) api_key ad_type:(NSString*) ad_type ad_id:(NSNumber*) ad_id __target:(id<FHBSoapServiceResponse>) __target;
-(NSMutableURLRequest*) createsearch_saleRequest:(NSString*) api_key query:(FHBsearch_query*) query __request:(FHBRequestResultHandler*) __request;
-(FHBsale_results*) search_sale:(NSString*) api_key query:(FHBsearch_query*) query __error:(NSError**) __error;
-(FHBRequestResultHandler*) search_saleAsync:(NSString*) api_key query:(FHBsearch_query*) query __target:(id) __target __handler:(SEL) __handler;
-(FHBRequestResultHandler*) search_saleAsync:(NSString*) api_key query:(FHBsearch_query*) query __target:(id<FHBSoapServiceResponse>) __target;
-(NSString*) search_rental:(NSString*) api_key query:(NSString*) query __error:(NSError**) __error;
-(FHBRequestResultHandler*) search_rentalAsync:(NSString*) api_key query:(NSString*) query __target:(id) __target __handler:(SEL) __handler;
-(FHBRequestResultHandler*) search_rentalAsync:(NSString*) api_key query:(NSString*) query __target:(id<FHBSoapServiceResponse>) __target;
-(NSString*) search_commercial:(NSString*) api_key query:(NSString*) query __error:(NSError**) __error;
-(FHBRequestResultHandler*) search_commercialAsync:(NSString*) api_key query:(NSString*) query __target:(id) __target __handler:(SEL) __handler;
-(FHBRequestResultHandler*) search_commercialAsync:(NSString*) api_key query:(NSString*) query __target:(id<FHBSoapServiceResponse>) __target;
-(NSString*) search_new_development:(NSString*) api_key query:(NSString*) query __error:(NSError**) __error;
-(FHBRequestResultHandler*) search_new_developmentAsync:(NSString*) api_key query:(NSString*) query __target:(id) __target __handler:(SEL) __handler;
-(FHBRequestResultHandler*) search_new_developmentAsync:(NSString*) api_key query:(NSString*) query __target:(id<FHBSoapServiceResponse>) __target;
-(NSString*) search_shortterm:(NSString*) api_key query:(NSString*) query __error:(NSError**) __error;
-(FHBRequestResultHandler*) search_shorttermAsync:(NSString*) api_key query:(NSString*) query __target:(id) __target __handler:(SEL) __handler;
-(FHBRequestResultHandler*) search_shorttermAsync:(NSString*) api_key query:(NSString*) query __target:(id<FHBSoapServiceResponse>) __target;
-(NSString*) search_sharing:(NSString*) api_key query:(NSString*) query __error:(NSError**) __error;
-(FHBRequestResultHandler*) search_sharingAsync:(NSString*) api_key query:(NSString*) query __target:(id) __target __handler:(SEL) __handler;
-(FHBRequestResultHandler*) search_sharingAsync:(NSString*) api_key query:(NSString*) query __target:(id<FHBSoapServiceResponse>) __target;
-(NSString*) search_parking:(NSString*) api_key query:(NSString*) query __error:(NSError**) __error;
-(FHBRequestResultHandler*) search_parkingAsync:(NSString*) api_key query:(NSString*) query __target:(id) __target __handler:(SEL) __handler;
-(FHBRequestResultHandler*) search_parkingAsync:(NSString*) api_key query:(NSString*) query __target:(id<FHBSoapServiceResponse>) __target;
-(NSString*) agent_info:(NSString*) api_key ad_id:(NSString*) ad_id ad_type:(NSString*) ad_type __error:(NSError**) __error;
-(FHBRequestResultHandler*) agent_infoAsync:(NSString*) api_key ad_id:(NSString*) ad_id ad_type:(NSString*) ad_type __target:(id) __target __handler:(SEL) __handler;
-(FHBRequestResultHandler*) agent_infoAsync:(NSString*) api_key ad_id:(NSString*) ad_id ad_type:(NSString*) ad_type __target:(id<FHBSoapServiceResponse>) __target;
-(FHBRequestResultHandler*) CreateRequestResultHandler;   
-(NSMutableURLRequest*) createRequest :(NSString*) soapAction __request:(FHBRequestResultHandler*) __request; 
-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(FHBRequestResultHandler*) requestMgr; 
-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(FHBRequestResultHandler*) requestMgr callback:(void (^)(FHBRequestResultHandler *)) callback;

@end
