//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.2.1
//
// Created by Quasar Development at 03-05-2014
//
//---------------------------------------------------


#import "FHBHelper.h"
#import "FHBimage.h"


@implementation FHBimage
@synthesize caption;
@synthesize large_url;
@synthesize medium_url;
@synthesize iphone_url;
@synthesize ipad_search_url;
@synthesize ipad_gallery_url;
@synthesize small_url;

+ (FHBimage *)createWithXml:(DDXMLElement *)__node __request:(FHBRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(FHBRequestResultHandler*) __request{
    if(self = [self init])
    {
        if([FHBHelper hasValue:__node name:@"caption" index:0])
        {
            self.caption = [[FHBHelper getNode:__node name:@"caption" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"large_url" index:0])
        {
            self.large_url = [[FHBHelper getNode:__node name:@"large_url" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"medium_url" index:0])
        {
            self.medium_url = [[FHBHelper getNode:__node name:@"medium_url" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"iphone_url" index:0])
        {
            self.iphone_url = [[FHBHelper getNode:__node name:@"iphone_url" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"ipad_search_url" index:0])
        {
            self.ipad_search_url = [[FHBHelper getNode:__node name:@"ipad_search_url" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"ipad_gallery_url" index:0])
        {
            self.ipad_gallery_url = [[FHBHelper getNode:__node name:@"ipad_gallery_url" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"small_url" index:0])
        {
            self.small_url = [[FHBHelper getNode:__node name:@"small_url" index:0] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(FHBRequestResultHandler*) __request
{

             
        DDXMLElement* __captionItemElement=[__request writeElement:caption type:[NSString class] name:@"caption" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__captionItemElement!=nil)
        {
            [__captionItemElement setStringValue:self.caption];
        }
             
        DDXMLElement* __large_urlItemElement=[__request writeElement:large_url type:[NSString class] name:@"large_url" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__large_urlItemElement!=nil)
        {
            [__large_urlItemElement setStringValue:self.large_url];
        }
             
        DDXMLElement* __medium_urlItemElement=[__request writeElement:medium_url type:[NSString class] name:@"medium_url" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__medium_urlItemElement!=nil)
        {
            [__medium_urlItemElement setStringValue:self.medium_url];
        }
             
        DDXMLElement* __iphone_urlItemElement=[__request writeElement:iphone_url type:[NSString class] name:@"iphone_url" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__iphone_urlItemElement!=nil)
        {
            [__iphone_urlItemElement setStringValue:self.iphone_url];
        }
             
        DDXMLElement* __ipad_search_urlItemElement=[__request writeElement:ipad_search_url type:[NSString class] name:@"ipad_search_url" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ipad_search_urlItemElement!=nil)
        {
            [__ipad_search_urlItemElement setStringValue:self.ipad_search_url];
        }
             
        DDXMLElement* __ipad_gallery_urlItemElement=[__request writeElement:ipad_gallery_url type:[NSString class] name:@"ipad_gallery_url" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ipad_gallery_urlItemElement!=nil)
        {
            [__ipad_gallery_urlItemElement setStringValue:self.ipad_gallery_url];
        }
             
        DDXMLElement* __small_urlItemElement=[__request writeElement:small_url type:[NSString class] name:@"small_url" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__small_urlItemElement!=nil)
        {
            [__small_urlItemElement setStringValue:self.small_url];
        }


}
@end
