//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.2.1
//
// Created by Quasar Development at 03-05-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

#import "FHBRequestResultHandler.h"
#import "DDXML.h"



@interface FHBimage : NSObject 


@property (retain,nonatomic,getter=getCaption) NSString* caption;

@property (retain,nonatomic,getter=getLarge_url) NSString* large_url;

@property (retain,nonatomic,getter=getMedium_url) NSString* medium_url;

@property (retain,nonatomic,getter=getIphone_url) NSString* iphone_url;

@property (retain,nonatomic,getter=getIpad_search_url) NSString* ipad_search_url;

@property (retain,nonatomic,getter=getIpad_gallery_url) NSString* ipad_gallery_url;

@property (retain,nonatomic,getter=getSmall_url) NSString* small_url;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(FHBRequestResultHandler*) __request;
+(FHBimage*) createWithXml:(DDXMLElement*)__node __request:(FHBRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(FHBRequestResultHandler*) __request;
@end