//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.2.1
//
// Created by Quasar Development at 03-05-2014
//
//---------------------------------------------------


#import "FHBHelper.h"
#import "FHBimage.h"
#import "FHBvirtualtour.h"
#import "FHBdocument.h"
#import "FHBmedia.h"


@implementation FHBmedia
@synthesize ad_type;
@synthesize ad_id;
@synthesize images;
@synthesize virtualtours;
@synthesize documents;

+ (FHBmedia *)createWithXml:(DDXMLElement *)__node __request:(FHBRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.ad_id =[NSNumber numberWithInt:0];
        self.images =[NSMutableArray array];
        self.virtualtours =[NSMutableArray array];
        self.documents =[NSMutableArray array];
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(FHBRequestResultHandler*) __request{
    if(self = [self init])
    {
        if([FHBHelper hasValue:__node name:@"ad_type" index:0])
        {
            self.ad_type = [[FHBHelper getNode:__node name:@"ad_type" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"ad_id" index:0])
        {
            self.ad_id = [FHBHelper getNumber:[[FHBHelper getNode:__node name:@"ad_id" index:0] stringValue]];
        }
        if([FHBHelper hasValue:__node name:@"images"])
        {
            NSArray* __items=[__node elementsForName:@"images"];
            for (DDXMLElement* __item in __items) {
                [self.images addObject:(FHBimage*)[__request createObject:__item type:[FHBimage class]]];
            }
        }
        if([FHBHelper hasValue:__node name:@"virtualtours"])
        {
            NSArray* __items=[__node elementsForName:@"virtualtours"];
            for (DDXMLElement* __item in __items) {
                [self.virtualtours addObject:(FHBvirtualtour*)[__request createObject:__item type:[FHBvirtualtour class]]];
            }
        }
        if([FHBHelper hasValue:__node name:@"documents"])
        {
            NSArray* __items=[__node elementsForName:@"documents"];
            for (DDXMLElement* __item in __items) {
                [self.documents addObject:(FHBdocument*)[__request createObject:__item type:[FHBdocument class]]];
            }
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(FHBRequestResultHandler*) __request
{

             
        DDXMLElement* __ad_typeItemElement=[__request writeElement:ad_type type:[NSString class] name:@"ad_type" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ad_typeItemElement!=nil)
        {
            [__ad_typeItemElement setStringValue:self.ad_type];
        }
             
        DDXMLElement* __ad_idItemElement=[__request writeElement:ad_id type:[NSNumber class] name:@"ad_id" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ad_idItemElement!=nil)
        {
            [__ad_idItemElement setStringValue:[self.ad_id stringValue]];
        }
             
        if(self.images!=nil)
        {
            for (FHBimage* __item in self.images) {
                DDXMLElement* __imagesItemElement=[__request writeElement:images type:[FHBimage class] name:@"images" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:NO];
                if(__imagesItemElement!=nil)
                {
                    [__item serialize:__imagesItemElement __request: __request];
                }
            }
        }
             
        if(self.virtualtours!=nil)
        {
            for (FHBvirtualtour* __item in self.virtualtours) {
                DDXMLElement* __virtualtoursItemElement=[__request writeElement:virtualtours type:[FHBvirtualtour class] name:@"virtualtours" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:NO];
                if(__virtualtoursItemElement!=nil)
                {
                    [__item serialize:__virtualtoursItemElement __request: __request];
                }
            }
        }
             
        if(self.documents!=nil)
        {
            for (FHBdocument* __item in self.documents) {
                DDXMLElement* __documentsItemElement=[__request writeElement:documents type:[FHBdocument class] name:@"documents" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:NO];
                if(__documentsItemElement!=nil)
                {
                    [__item serialize:__documentsItemElement __request: __request];
                }
            }
        }


}
@end
