//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.2.1
//
// Created by Quasar Development at 03-05-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class FHBHelper;
@class FHBimage;
@class FHBvirtualtour;
@class FHBdocument;
#import "FHBRequestResultHandler.h"
#import "DDXML.h"



@interface FHBmedia : NSObject 


@property (retain,nonatomic,getter=getAd_type) NSString* ad_type;

@property (retain,nonatomic,getter=getAd_id) NSNumber* ad_id;

@property (retain,nonatomic,getter=getImages) NSMutableArray* images;

@property (retain,nonatomic,getter=getVirtualtours) NSMutableArray* virtualtours;

@property (retain,nonatomic,getter=getDocuments) NSMutableArray* documents;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(FHBRequestResultHandler*) __request;
+(FHBmedia*) createWithXml:(DDXMLElement*)__node __request:(FHBRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(FHBRequestResultHandler*) __request;
@end