//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.2.1
//
// Created by Quasar Development at 03-05-2014
//
//---------------------------------------------------


#import "FHBHelper.h"
#import "FHBpagination.h"


@implementation FHBpagination
@synthesize total_results;
@synthesize results_per_page;
@synthesize num_pages;
@synthesize current_page;
@synthesize first_on_page;
@synthesize last_on_page;

+ (FHBpagination *)createWithXml:(DDXMLElement *)__node __request:(FHBRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(FHBRequestResultHandler*) __request{
    if(self = [self init])
    {
        if([FHBHelper hasValue:__node name:@"total_results" index:0])
        {
            self.total_results = [FHBHelper getNumber:[[FHBHelper getNode:__node name:@"total_results" index:0] stringValue]];
        }
        if([FHBHelper hasValue:__node name:@"results_per_page" index:0])
        {
            self.results_per_page = [FHBHelper getNumber:[[FHBHelper getNode:__node name:@"results_per_page" index:0] stringValue]];
        }
        if([FHBHelper hasValue:__node name:@"num_pages" index:0])
        {
            self.num_pages = [FHBHelper getNumber:[[FHBHelper getNode:__node name:@"num_pages" index:0] stringValue]];
        }
        if([FHBHelper hasValue:__node name:@"current_page" index:0])
        {
            self.current_page = [FHBHelper getNumber:[[FHBHelper getNode:__node name:@"current_page" index:0] stringValue]];
        }
        if([FHBHelper hasValue:__node name:@"first_on_page" index:0])
        {
            self.first_on_page = [FHBHelper getNumber:[[FHBHelper getNode:__node name:@"first_on_page" index:0] stringValue]];
        }
        if([FHBHelper hasValue:__node name:@"last_on_page" index:0])
        {
            self.last_on_page = [FHBHelper getNumber:[[FHBHelper getNode:__node name:@"last_on_page" index:0] stringValue]];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(FHBRequestResultHandler*) __request
{

             
        DDXMLElement* __total_resultsItemElement=[__request writeElement:total_results type:[NSNumber class] name:@"total_results" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__total_resultsItemElement!=nil)
        {
            [__total_resultsItemElement setStringValue:[self.total_results stringValue]];
        }
             
        DDXMLElement* __results_per_pageItemElement=[__request writeElement:results_per_page type:[NSNumber class] name:@"results_per_page" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__results_per_pageItemElement!=nil)
        {
            [__results_per_pageItemElement setStringValue:[self.results_per_page stringValue]];
        }
             
        DDXMLElement* __num_pagesItemElement=[__request writeElement:num_pages type:[NSNumber class] name:@"num_pages" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__num_pagesItemElement!=nil)
        {
            [__num_pagesItemElement setStringValue:[self.num_pages stringValue]];
        }
             
        DDXMLElement* __current_pageItemElement=[__request writeElement:current_page type:[NSNumber class] name:@"current_page" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__current_pageItemElement!=nil)
        {
            [__current_pageItemElement setStringValue:[self.current_page stringValue]];
        }
             
        DDXMLElement* __first_on_pageItemElement=[__request writeElement:first_on_page type:[NSNumber class] name:@"first_on_page" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__first_on_pageItemElement!=nil)
        {
            [__first_on_pageItemElement setStringValue:[self.first_on_page stringValue]];
        }
             
        DDXMLElement* __last_on_pageItemElement=[__request writeElement:last_on_page type:[NSNumber class] name:@"last_on_page" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__last_on_pageItemElement!=nil)
        {
            [__last_on_pageItemElement setStringValue:[self.last_on_page stringValue]];
        }


}
@end
