//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.2.1
//
// Created by Quasar Development at 03-05-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class FHBHelper;
#import "FHBRequestResultHandler.h"
#import "DDXML.h"



@interface FHBpagination : NSObject 


@property (retain,nonatomic,getter=getTotal_results) NSNumber* total_results;

@property (retain,nonatomic,getter=getResults_per_page) NSNumber* results_per_page;

@property (retain,nonatomic,getter=getNum_pages) NSNumber* num_pages;

@property (retain,nonatomic,getter=getCurrent_page) NSNumber* current_page;

@property (retain,nonatomic,getter=getFirst_on_page) NSNumber* first_on_page;

@property (retain,nonatomic,getter=getLast_on_page) NSNumber* last_on_page;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(FHBRequestResultHandler*) __request;
+(FHBpagination*) createWithXml:(DDXMLElement*)__node __request:(FHBRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(FHBRequestResultHandler*) __request;
@end