//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.2.1
//
// Created by Quasar Development at 03-05-2014
//
//---------------------------------------------------


#import "FHBHelper.h"
#import "FHBproperty_type.h"


@implementation FHBproperty_type
@synthesize name;
@synthesize plural;
@synthesize _short;
@synthesize short_plural;
@synthesize key;

+ (FHBproperty_type *)createWithXml:(DDXMLElement *)__node __request:(FHBRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(FHBRequestResultHandler*) __request{
    if(self = [self init])
    {
        if([FHBHelper hasValue:__node name:@"name" index:0])
        {
            self.name = [[FHBHelper getNode:__node name:@"name" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"plural" index:0])
        {
            self.plural = [[FHBHelper getNode:__node name:@"plural" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"short" index:0])
        {
            self._short = [[FHBHelper getNode:__node name:@"short" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"short_plural" index:0])
        {
            self.short_plural = [[FHBHelper getNode:__node name:@"short_plural" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"key" index:0])
        {
            self.key = [[FHBHelper getNode:__node name:@"key" index:0] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(FHBRequestResultHandler*) __request
{

             
        DDXMLElement* __nameItemElement=[__request writeElement:name type:[NSString class] name:@"name" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__nameItemElement!=nil)
        {
            [__nameItemElement setStringValue:self.name];
        }
             
        DDXMLElement* __pluralItemElement=[__request writeElement:plural type:[NSString class] name:@"plural" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__pluralItemElement!=nil)
        {
            [__pluralItemElement setStringValue:self.plural];
        }
             
        DDXMLElement* ___shortItemElement=[__request writeElement:_short type:[NSString class] name:@"short" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(___shortItemElement!=nil)
        {
            [___shortItemElement setStringValue:self._short];
        }
             
        DDXMLElement* __short_pluralItemElement=[__request writeElement:short_plural type:[NSString class] name:@"short_plural" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__short_pluralItemElement!=nil)
        {
            [__short_pluralItemElement setStringValue:self.short_plural];
        }
             
        DDXMLElement* __keyItemElement=[__request writeElement:key type:[NSString class] name:@"key" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__keyItemElement!=nil)
        {
            [__keyItemElement setStringValue:self.key];
        }


}
@end
