//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.2.1
//
// Created by Quasar Development at 03-05-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class FHBHelper;
#import "FHBRequestResultHandler.h"
#import "DDXML.h"



@interface FHBsearch_query : NSObject 


@property (retain,nonatomic,getter=getAd_ids) NSMutableArray* ad_ids;

@property (retain,nonatomic,getter=getProperty_type) NSMutableArray* property_type;

@property (retain,nonatomic,getter=getHouse_type) NSString* house_type;

@property (retain,nonatomic,getter=getBedrooms) NSNumber* bedrooms;

@property (retain,nonatomic,getter=getMin_bedrooms) NSNumber* min_bedrooms;

@property (retain,nonatomic,getter=getMax_bedrooms) NSNumber* max_bedrooms;

@property (retain,nonatomic,getter=getMin_price) NSNumber* min_price;

@property (retain,nonatomic,getter=getMax_price) NSNumber* max_price;

@property (retain,nonatomic,getter=getTxt) NSString* txt;

@property (retain,nonatomic,getter=getAgreed) NSNumber* agreed;

@property (retain,nonatomic,getter=getDays_old) NSNumber* days_old;

@property (retain,nonatomic,getter=getImages) NSNumber* images;

@property (retain,nonatomic,getter=getAgent_id) NSNumber* agent_id;

@property (retain,nonatomic,getter=getInstitute_id) NSNumber* institute_id;

@property (retain,nonatomic,getter=getEdited_since) NSNumber* edited_since;

@property (retain,nonatomic,getter=getFeatures) NSMutableArray* features;

@property (retain,nonatomic,getter=getAvailable_date) NSNumber* available_date;

@property (retain,nonatomic,getter=getLease_length) NSNumber* lease_length;

@property (retain,nonatomic,getter=getFurnished) NSNumber* furnished;

@property (retain,nonatomic,getter=getRent_allowance) NSNumber* rent_allowance;

@property (retain,nonatomic,getter=getSingle_beds) NSNumber* single_beds;

@property (retain,nonatomic,getter=getDouble_beds) NSNumber* double_beds;

@property (retain,nonatomic,getter=getTwin_beds) NSNumber* twin_beds;

@property (retain,nonatomic,getter=getBedroom_type) NSString* bedroom_type;

@property (retain,nonatomic,getter=getOwner_occupied) NSNumber* owner_occupied;

@property (retain,nonatomic,getter=getOccupants) NSNumber* occupants;

@property (retain,nonatomic,getter=getGender) NSString* gender;

@property (retain,nonatomic,getter=getCouples_allowed) NSNumber* couples_allowed;

@property (retain,nonatomic,getter=getAvailable_for) NSString* available_for;

@property (retain,nonatomic,getter=getMin_sq_ft) NSNumber* min_sq_ft;

@property (retain,nonatomic,getter=getMax_sq_ft) NSNumber* max_sq_ft;

@property (retain,nonatomic,getter=getContract_type) NSNumber* contract_type;

@property (retain,nonatomic,getter=getSleeps_number) NSNumber* sleeps_number;

@property (retain,nonatomic,getter=getCounties) NSMutableArray* counties;

@property (retain,nonatomic,getter=getCities) NSMutableArray* cities;

@property (retain,nonatomic,getter=getGeneral_areas) NSMutableArray* general_areas;

@property (retain,nonatomic,getter=getAreas) NSMutableArray* areas;

@property (retain,nonatomic,getter=getPostcodes) NSMutableArray* postcodes;

@property (retain,nonatomic,getter=getAddress) NSString* address;

@property (retain,nonatomic,getter=getCountry) NSString* country;

@property (retain,nonatomic,getter=getPerpage) NSNumber* perpage;

@property (retain,nonatomic,getter=getPage) NSNumber* page;

@property (retain,nonatomic,getter=getSort_by) NSString* sort_by;

@property (retain,nonatomic,getter=getSort_ascending) NSNumber* sort_ascending;

@property (retain,nonatomic,getter=getDistance_sort_latitude) NSNumber* distance_sort_latitude;

@property (retain,nonatomic,getter=getDistance_sort_longitude) NSNumber* distance_sort_longitude;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(FHBRequestResultHandler*) __request;
+(FHBsearch_query*) createWithXml:(DDXMLElement*)__node __request:(FHBRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(FHBRequestResultHandler*) __request;
@end