//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.2.1
//
// Created by Quasar Development at 03-05-2014
//
//---------------------------------------------------


#import "FHBHelper.h"
#import "FHBsale_ad.h"


@implementation FHBsale_ad
@synthesize ad_id;
@synthesize daft_url;
@synthesize property_type;
@synthesize house_type;
@synthesize selling_type;
@synthesize price_type;
@synthesize agreed;
@synthesize priority;
@synthesize description;
@synthesize price;
@synthesize bedrooms;
@synthesize bathrooms;
@synthesize tax_section;
@synthesize square_metres;
@synthesize acres;
@synthesize features;
@synthesize ber_rating;
@synthesize ber_code;
@synthesize ber_epi;
@synthesize address;
@synthesize full_address;
@synthesize area;
@synthesize county;
@synthesize city;
@synthesize general_area;
@synthesize postcode;
@synthesize latitude;
@synthesize longitude;
@synthesize latlon_accuracy;
@synthesize agency_name;
@synthesize contact_name;
@synthesize phone1;
@synthesize phone2;
@synthesize phoneinfo;
@synthesize main_email;
@synthesize cc_email;
@synthesize auction_address;
@synthesize start_date;
@synthesize listing_date;
@synthesize agreed_date;
@synthesize auction_date;
@synthesize small_thumbnail_url;
@synthesize medium_thumbnail_url;
@synthesize large_thumbnail_url;
@synthesize ipad_search_url;
@synthesize ipad_gallery_url;
@synthesize tags;

+ (FHBsale_ad *)createWithXml:(DDXMLElement *)__node __request:(FHBRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.features =[NSMutableArray array];
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(FHBRequestResultHandler*) __request{
    if(self = [self init])
    {
        if([FHBHelper hasValue:__node name:@"ad_id" index:0])
        {
            self.ad_id = [FHBHelper getNumber:[[FHBHelper getNode:__node name:@"ad_id" index:0] stringValue]];
        }
        if([FHBHelper hasValue:__node name:@"daft_url" index:0])
        {
            self.daft_url = [[FHBHelper getNode:__node name:@"daft_url" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"property_type" index:0])
        {
            self.property_type = [[FHBHelper getNode:__node name:@"property_type" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"house_type" index:0])
        {
            self.house_type = [[FHBHelper getNode:__node name:@"house_type" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"selling_type" index:0])
        {
            self.selling_type = [[FHBHelper getNode:__node name:@"selling_type" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"price_type" index:0])
        {
            self.price_type = [[FHBHelper getNode:__node name:@"price_type" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"agreed" index:0])
        {
            self.agreed = [FHBHelper getNumber:[[FHBHelper getNode:__node name:@"agreed" index:0] stringValue]];
        }
        if([FHBHelper hasValue:__node name:@"priority" index:0])
        {
            self.priority = [FHBHelper getNumber:[[FHBHelper getNode:__node name:@"priority" index:0] stringValue]];
        }
        if([FHBHelper hasValue:__node name:@"description" index:0])
        {
            self.description = [[FHBHelper getNode:__node name:@"description" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"price" index:0])
        {
            self.price = [FHBHelper getNumber:[[FHBHelper getNode:__node name:@"price" index:0] stringValue]];
        }
        if([FHBHelper hasValue:__node name:@"bedrooms" index:0])
        {
            self.bedrooms = [FHBHelper getNumber:[[FHBHelper getNode:__node name:@"bedrooms" index:0] stringValue]];
        }
        if([FHBHelper hasValue:__node name:@"bathrooms" index:0])
        {
            self.bathrooms = [FHBHelper getNumber:[[FHBHelper getNode:__node name:@"bathrooms" index:0] stringValue]];
        }
        if([FHBHelper hasValue:__node name:@"tax_section" index:0])
        {
            self.tax_section = [[FHBHelper getNode:__node name:@"tax_section" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"square_metres" index:0])
        {
            self.square_metres = [FHBHelper getNumber:[[FHBHelper getNode:__node name:@"square_metres" index:0] stringValue]];
        }
        if([FHBHelper hasValue:__node name:@"acres" index:0])
        {
            self.acres = [FHBHelper getNumber:[[FHBHelper getNode:__node name:@"acres" index:0] stringValue]];
        }
        if([FHBHelper hasValue:__node name:@"features"])
        {
            NSArray* __items=[__node elementsForName:@"features"];
            for (DDXMLElement* __item in __items) {
                [self.features addObject:[__item stringValue]];
            }
        }
        if([FHBHelper hasValue:__node name:@"ber_rating" index:0])
        {
            self.ber_rating = [[FHBHelper getNode:__node name:@"ber_rating" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"ber_code" index:0])
        {
            self.ber_code = [[FHBHelper getNode:__node name:@"ber_code" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"ber_epi" index:0])
        {
            self.ber_epi = [FHBHelper getNumber:[[FHBHelper getNode:__node name:@"ber_epi" index:0] stringValue]];
        }
        if([FHBHelper hasValue:__node name:@"address" index:0])
        {
            self.address = [[FHBHelper getNode:__node name:@"address" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"full_address" index:0])
        {
            self.full_address = [[FHBHelper getNode:__node name:@"full_address" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"area" index:0])
        {
            self.area = [[FHBHelper getNode:__node name:@"area" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"county" index:0])
        {
            self.county = [[FHBHelper getNode:__node name:@"county" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"city" index:0])
        {
            self.city = [[FHBHelper getNode:__node name:@"city" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"general_area" index:0])
        {
            self.general_area = [[FHBHelper getNode:__node name:@"general_area" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"postcode" index:0])
        {
            self.postcode = [[FHBHelper getNode:__node name:@"postcode" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"latitude" index:0])
        {
            self.latitude = [FHBHelper getNumber:[[FHBHelper getNode:__node name:@"latitude" index:0] stringValue]];
        }
        if([FHBHelper hasValue:__node name:@"longitude" index:0])
        {
            self.longitude = [FHBHelper getNumber:[[FHBHelper getNode:__node name:@"longitude" index:0] stringValue]];
        }
        if([FHBHelper hasValue:__node name:@"latlon_accuracy" index:0])
        {
            self.latlon_accuracy = [FHBHelper getNumber:[[FHBHelper getNode:__node name:@"latlon_accuracy" index:0] stringValue]];
        }
        if([FHBHelper hasValue:__node name:@"agency_name" index:0])
        {
            self.agency_name = [[FHBHelper getNode:__node name:@"agency_name" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"contact_name" index:0])
        {
            self.contact_name = [[FHBHelper getNode:__node name:@"contact_name" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"phone1" index:0])
        {
            self.phone1 = [[FHBHelper getNode:__node name:@"phone1" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"phone2" index:0])
        {
            self.phone2 = [[FHBHelper getNode:__node name:@"phone2" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"phoneinfo" index:0])
        {
            self.phoneinfo = [[FHBHelper getNode:__node name:@"phoneinfo" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"main_email" index:0])
        {
            self.main_email = [[FHBHelper getNode:__node name:@"main_email" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"cc_email" index:0])
        {
            self.cc_email = [[FHBHelper getNode:__node name:@"cc_email" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"auction_address" index:0])
        {
            self.auction_address = [[FHBHelper getNode:__node name:@"auction_address" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"start_date" index:0])
        {
            self.start_date = [FHBHelper getNumber:[[FHBHelper getNode:__node name:@"start_date" index:0] stringValue]];
        }
        if([FHBHelper hasValue:__node name:@"listing_date" index:0])
        {
            self.listing_date = [FHBHelper getNumber:[[FHBHelper getNode:__node name:@"listing_date" index:0] stringValue]];
        }
        if([FHBHelper hasValue:__node name:@"agreed_date" index:0])
        {
            self.agreed_date = [FHBHelper getNumber:[[FHBHelper getNode:__node name:@"agreed_date" index:0] stringValue]];
        }
        if([FHBHelper hasValue:__node name:@"auction_date" index:0])
        {
            self.auction_date = [FHBHelper getNumber:[[FHBHelper getNode:__node name:@"auction_date" index:0] stringValue]];
        }
        if([FHBHelper hasValue:__node name:@"small_thumbnail_url" index:0])
        {
            self.small_thumbnail_url = [[FHBHelper getNode:__node name:@"small_thumbnail_url" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"medium_thumbnail_url" index:0])
        {
            self.medium_thumbnail_url = [[FHBHelper getNode:__node name:@"medium_thumbnail_url" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"large_thumbnail_url" index:0])
        {
            self.large_thumbnail_url = [[FHBHelper getNode:__node name:@"large_thumbnail_url" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"ipad_search_url" index:0])
        {
            self.ipad_search_url = [[FHBHelper getNode:__node name:@"ipad_search_url" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"ipad_gallery_url" index:0])
        {
            self.ipad_gallery_url = [[FHBHelper getNode:__node name:@"ipad_gallery_url" index:0] stringValue];
        }
        if([FHBHelper hasValue:__node name:@"tags" index:0])
        {
            self.tags = [FHBHelper getNumber:[[FHBHelper getNode:__node name:@"tags" index:0] stringValue]];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(FHBRequestResultHandler*) __request
{

             
        DDXMLElement* __ad_idItemElement=[__request writeElement:ad_id type:[NSNumber class] name:@"ad_id" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ad_idItemElement!=nil)
        {
            [__ad_idItemElement setStringValue:[self.ad_id stringValue]];
        }
             
        DDXMLElement* __daft_urlItemElement=[__request writeElement:daft_url type:[NSString class] name:@"daft_url" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__daft_urlItemElement!=nil)
        {
            [__daft_urlItemElement setStringValue:self.daft_url];
        }
             
        DDXMLElement* __property_typeItemElement=[__request writeElement:property_type type:[NSString class] name:@"property_type" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__property_typeItemElement!=nil)
        {
            [__property_typeItemElement setStringValue:self.property_type];
        }
             
        DDXMLElement* __house_typeItemElement=[__request writeElement:house_type type:[NSString class] name:@"house_type" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__house_typeItemElement!=nil)
        {
            [__house_typeItemElement setStringValue:self.house_type];
        }
             
        DDXMLElement* __selling_typeItemElement=[__request writeElement:selling_type type:[NSString class] name:@"selling_type" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__selling_typeItemElement!=nil)
        {
            [__selling_typeItemElement setStringValue:self.selling_type];
        }
             
        DDXMLElement* __price_typeItemElement=[__request writeElement:price_type type:[NSString class] name:@"price_type" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__price_typeItemElement!=nil)
        {
            [__price_typeItemElement setStringValue:self.price_type];
        }
             
        DDXMLElement* __agreedItemElement=[__request writeElement:agreed type:[NSNumber class] name:@"agreed" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__agreedItemElement!=nil)
        {
            [__agreedItemElement setStringValue:[self.agreed stringValue]];
        }
             
        DDXMLElement* __priorityItemElement=[__request writeElement:priority type:[NSNumber class] name:@"priority" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__priorityItemElement!=nil)
        {
            [__priorityItemElement setStringValue:[self.priority stringValue]];
        }
             
        DDXMLElement* __descriptionItemElement=[__request writeElement:description type:[NSString class] name:@"description" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__descriptionItemElement!=nil)
        {
            [__descriptionItemElement setStringValue:self.description];
        }
             
        DDXMLElement* __priceItemElement=[__request writeElement:price type:[NSNumber class] name:@"price" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__priceItemElement!=nil)
        {
            [__priceItemElement setStringValue:[self.price stringValue]];
        }
             
        DDXMLElement* __bedroomsItemElement=[__request writeElement:bedrooms type:[NSNumber class] name:@"bedrooms" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__bedroomsItemElement!=nil)
        {
            [__bedroomsItemElement setStringValue:[self.bedrooms stringValue]];
        }
             
        DDXMLElement* __bathroomsItemElement=[__request writeElement:bathrooms type:[NSNumber class] name:@"bathrooms" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__bathroomsItemElement!=nil)
        {
            [__bathroomsItemElement setStringValue:[self.bathrooms stringValue]];
        }
             
        DDXMLElement* __tax_sectionItemElement=[__request writeElement:tax_section type:[NSString class] name:@"tax_section" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__tax_sectionItemElement!=nil)
        {
            [__tax_sectionItemElement setStringValue:self.tax_section];
        }
             
        DDXMLElement* __square_metresItemElement=[__request writeElement:square_metres type:[NSNumber class] name:@"square_metres" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__square_metresItemElement!=nil)
        {
            [__square_metresItemElement setStringValue:[self.square_metres stringValue]];
        }
             
        DDXMLElement* __acresItemElement=[__request writeElement:acres type:[NSNumber class] name:@"acres" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__acresItemElement!=nil)
        {
            [__acresItemElement setStringValue:[self.acres stringValue]];
        }
             
        if(self.features!=nil)
        {
            for (NSString* __item in self.features) {
                DDXMLElement* __featuresItemElement=[__request writeElement:features type:[NSString class] name:@"features" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:NO];
                if(__featuresItemElement!=nil)
                {
                    [__featuresItemElement setStringValue:__item];
                }
            }
        }
             
        DDXMLElement* __ber_ratingItemElement=[__request writeElement:ber_rating type:[NSString class] name:@"ber_rating" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ber_ratingItemElement!=nil)
        {
            [__ber_ratingItemElement setStringValue:self.ber_rating];
        }
             
        DDXMLElement* __ber_codeItemElement=[__request writeElement:ber_code type:[NSString class] name:@"ber_code" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ber_codeItemElement!=nil)
        {
            [__ber_codeItemElement setStringValue:self.ber_code];
        }
             
        DDXMLElement* __ber_epiItemElement=[__request writeElement:ber_epi type:[NSNumber class] name:@"ber_epi" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ber_epiItemElement!=nil)
        {
            [__ber_epiItemElement setStringValue:[self.ber_epi stringValue]];
        }
             
        DDXMLElement* __addressItemElement=[__request writeElement:address type:[NSString class] name:@"address" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__addressItemElement!=nil)
        {
            [__addressItemElement setStringValue:self.address];
        }
             
        DDXMLElement* __full_addressItemElement=[__request writeElement:full_address type:[NSString class] name:@"full_address" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__full_addressItemElement!=nil)
        {
            [__full_addressItemElement setStringValue:self.full_address];
        }
             
        DDXMLElement* __areaItemElement=[__request writeElement:area type:[NSString class] name:@"area" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__areaItemElement!=nil)
        {
            [__areaItemElement setStringValue:self.area];
        }
             
        DDXMLElement* __countyItemElement=[__request writeElement:county type:[NSString class] name:@"county" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__countyItemElement!=nil)
        {
            [__countyItemElement setStringValue:self.county];
        }
             
        DDXMLElement* __cityItemElement=[__request writeElement:city type:[NSString class] name:@"city" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__cityItemElement!=nil)
        {
            [__cityItemElement setStringValue:self.city];
        }
             
        DDXMLElement* __general_areaItemElement=[__request writeElement:general_area type:[NSString class] name:@"general_area" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__general_areaItemElement!=nil)
        {
            [__general_areaItemElement setStringValue:self.general_area];
        }
             
        DDXMLElement* __postcodeItemElement=[__request writeElement:postcode type:[NSString class] name:@"postcode" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__postcodeItemElement!=nil)
        {
            [__postcodeItemElement setStringValue:self.postcode];
        }
             
        DDXMLElement* __latitudeItemElement=[__request writeElement:latitude type:[NSNumber class] name:@"latitude" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__latitudeItemElement!=nil)
        {
            [__latitudeItemElement setStringValue:[self.latitude stringValue]];
        }
             
        DDXMLElement* __longitudeItemElement=[__request writeElement:longitude type:[NSNumber class] name:@"longitude" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__longitudeItemElement!=nil)
        {
            [__longitudeItemElement setStringValue:[self.longitude stringValue]];
        }
             
        DDXMLElement* __latlon_accuracyItemElement=[__request writeElement:latlon_accuracy type:[NSNumber class] name:@"latlon_accuracy" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__latlon_accuracyItemElement!=nil)
        {
            [__latlon_accuracyItemElement setStringValue:[self.latlon_accuracy stringValue]];
        }
             
        DDXMLElement* __agency_nameItemElement=[__request writeElement:agency_name type:[NSString class] name:@"agency_name" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__agency_nameItemElement!=nil)
        {
            [__agency_nameItemElement setStringValue:self.agency_name];
        }
             
        DDXMLElement* __contact_nameItemElement=[__request writeElement:contact_name type:[NSString class] name:@"contact_name" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__contact_nameItemElement!=nil)
        {
            [__contact_nameItemElement setStringValue:self.contact_name];
        }
             
        DDXMLElement* __phone1ItemElement=[__request writeElement:phone1 type:[NSString class] name:@"phone1" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__phone1ItemElement!=nil)
        {
            [__phone1ItemElement setStringValue:self.phone1];
        }
             
        DDXMLElement* __phone2ItemElement=[__request writeElement:phone2 type:[NSString class] name:@"phone2" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__phone2ItemElement!=nil)
        {
            [__phone2ItemElement setStringValue:self.phone2];
        }
             
        DDXMLElement* __phoneinfoItemElement=[__request writeElement:phoneinfo type:[NSString class] name:@"phoneinfo" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__phoneinfoItemElement!=nil)
        {
            [__phoneinfoItemElement setStringValue:self.phoneinfo];
        }
             
        DDXMLElement* __main_emailItemElement=[__request writeElement:main_email type:[NSString class] name:@"main_email" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__main_emailItemElement!=nil)
        {
            [__main_emailItemElement setStringValue:self.main_email];
        }
             
        DDXMLElement* __cc_emailItemElement=[__request writeElement:cc_email type:[NSString class] name:@"cc_email" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__cc_emailItemElement!=nil)
        {
            [__cc_emailItemElement setStringValue:self.cc_email];
        }
             
        DDXMLElement* __auction_addressItemElement=[__request writeElement:auction_address type:[NSString class] name:@"auction_address" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__auction_addressItemElement!=nil)
        {
            [__auction_addressItemElement setStringValue:self.auction_address];
        }
             
        DDXMLElement* __start_dateItemElement=[__request writeElement:start_date type:[NSNumber class] name:@"start_date" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__start_dateItemElement!=nil)
        {
            [__start_dateItemElement setStringValue:[self.start_date stringValue]];
        }
             
        DDXMLElement* __listing_dateItemElement=[__request writeElement:listing_date type:[NSNumber class] name:@"listing_date" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__listing_dateItemElement!=nil)
        {
            [__listing_dateItemElement setStringValue:[self.listing_date stringValue]];
        }
             
        DDXMLElement* __agreed_dateItemElement=[__request writeElement:agreed_date type:[NSNumber class] name:@"agreed_date" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__agreed_dateItemElement!=nil)
        {
            [__agreed_dateItemElement setStringValue:[self.agreed_date stringValue]];
        }
             
        DDXMLElement* __auction_dateItemElement=[__request writeElement:auction_date type:[NSNumber class] name:@"auction_date" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__auction_dateItemElement!=nil)
        {
            [__auction_dateItemElement setStringValue:[self.auction_date stringValue]];
        }
             
        DDXMLElement* __small_thumbnail_urlItemElement=[__request writeElement:small_thumbnail_url type:[NSString class] name:@"small_thumbnail_url" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__small_thumbnail_urlItemElement!=nil)
        {
            [__small_thumbnail_urlItemElement setStringValue:self.small_thumbnail_url];
        }
             
        DDXMLElement* __medium_thumbnail_urlItemElement=[__request writeElement:medium_thumbnail_url type:[NSString class] name:@"medium_thumbnail_url" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__medium_thumbnail_urlItemElement!=nil)
        {
            [__medium_thumbnail_urlItemElement setStringValue:self.medium_thumbnail_url];
        }
             
        DDXMLElement* __large_thumbnail_urlItemElement=[__request writeElement:large_thumbnail_url type:[NSString class] name:@"large_thumbnail_url" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__large_thumbnail_urlItemElement!=nil)
        {
            [__large_thumbnail_urlItemElement setStringValue:self.large_thumbnail_url];
        }
             
        DDXMLElement* __ipad_search_urlItemElement=[__request writeElement:ipad_search_url type:[NSString class] name:@"ipad_search_url" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ipad_search_urlItemElement!=nil)
        {
            [__ipad_search_urlItemElement setStringValue:self.ipad_search_url];
        }
             
        DDXMLElement* __ipad_gallery_urlItemElement=[__request writeElement:ipad_gallery_url type:[NSString class] name:@"ipad_gallery_url" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ipad_gallery_urlItemElement!=nil)
        {
            [__ipad_gallery_urlItemElement setStringValue:self.ipad_gallery_url];
        }
             
        DDXMLElement* __tagsItemElement=[__request writeElement:tags type:[NSNumber class] name:@"tags" URI:@"http://api.daft.ie/v2/" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__tagsItemElement!=nil)
        {
            [__tagsItemElement setStringValue:[self.tags stringValue]];
        }


}
@end
