//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.2.1
//
// Created by Quasar Development at 03-05-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class FHBHelper;
#import "FHBRequestResultHandler.h"
#import "DDXML.h"



@interface FHBsale_ad : NSObject 


@property (retain,nonatomic,getter=getAd_id) NSNumber* ad_id;

@property (retain,nonatomic,getter=getDaft_url) NSString* daft_url;

@property (retain,nonatomic,getter=getProperty_type) NSString* property_type;

@property (retain,nonatomic,getter=getHouse_type) NSString* house_type;

@property (retain,nonatomic,getter=getSelling_type) NSString* selling_type;

@property (retain,nonatomic,getter=getPrice_type) NSString* price_type;

@property (retain,nonatomic,getter=getAgreed) NSNumber* agreed;

@property (retain,nonatomic,getter=getPriority) NSNumber* priority;

@property (retain,nonatomic,getter=getDescription) NSString* description;

@property (retain,nonatomic,getter=getPrice) NSNumber* price;

@property (retain,nonatomic,getter=getBedrooms) NSNumber* bedrooms;

@property (retain,nonatomic,getter=getBathrooms) NSNumber* bathrooms;

@property (retain,nonatomic,getter=getTax_section) NSString* tax_section;

@property (retain,nonatomic,getter=getSquare_metres) NSNumber* square_metres;

@property (retain,nonatomic,getter=getAcres) NSNumber* acres;

@property (retain,nonatomic,getter=getFeatures) NSMutableArray* features;

@property (retain,nonatomic,getter=getBer_rating) NSString* ber_rating;

@property (retain,nonatomic,getter=getBer_code) NSString* ber_code;

@property (retain,nonatomic,getter=getBer_epi) NSNumber* ber_epi;

@property (retain,nonatomic,getter=getAddress) NSString* address;

@property (retain,nonatomic,getter=getFull_address) NSString* full_address;

@property (retain,nonatomic,getter=getArea) NSString* area;

@property (retain,nonatomic,getter=getCounty) NSString* county;

@property (retain,nonatomic,getter=getCity) NSString* city;

@property (retain,nonatomic,getter=getGeneral_area) NSString* general_area;

@property (retain,nonatomic,getter=getPostcode) NSString* postcode;

@property (retain,nonatomic,getter=getLatitude) NSNumber* latitude;

@property (retain,nonatomic,getter=getLongitude) NSNumber* longitude;

@property (retain,nonatomic,getter=getLatlon_accuracy) NSNumber* latlon_accuracy;

@property (retain,nonatomic,getter=getAgency_name) NSString* agency_name;

@property (retain,nonatomic,getter=getContact_name) NSString* contact_name;

@property (retain,nonatomic,getter=getPhone1) NSString* phone1;

@property (retain,nonatomic,getter=getPhone2) NSString* phone2;

@property (retain,nonatomic,getter=getPhoneinfo) NSString* phoneinfo;

@property (retain,nonatomic,getter=getMain_email) NSString* main_email;

@property (retain,nonatomic,getter=getCc_email) NSString* cc_email;

@property (retain,nonatomic,getter=getAuction_address) NSString* auction_address;

@property (retain,nonatomic,getter=getStart_date) NSNumber* start_date;

@property (retain,nonatomic,getter=getListing_date) NSNumber* listing_date;

@property (retain,nonatomic,getter=getAgreed_date) NSNumber* agreed_date;

@property (retain,nonatomic,getter=getAuction_date) NSNumber* auction_date;

@property (retain,nonatomic,getter=getSmall_thumbnail_url) NSString* small_thumbnail_url;

@property (retain,nonatomic,getter=getMedium_thumbnail_url) NSString* medium_thumbnail_url;

@property (retain,nonatomic,getter=getLarge_thumbnail_url) NSString* large_thumbnail_url;

@property (retain,nonatomic,getter=getIpad_search_url) NSString* ipad_search_url;

@property (retain,nonatomic,getter=getIpad_gallery_url) NSString* ipad_gallery_url;

@property (retain,nonatomic,getter=getTags) NSNumber* tags;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(FHBRequestResultHandler*) __request;
+(FHBsale_ad*) createWithXml:(DDXMLElement*)__node __request:(FHBRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(FHBRequestResultHandler*) __request;
@end