//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.2.1
//
// Created by Quasar Development at 03-05-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

#import "FHBRequestResultHandler.h"
#import "DDXML.h"



@interface FHBvirtualtour : NSObject 


@property (retain,nonatomic,getter=getCaption) NSString* caption;

@property (retain,nonatomic,getter=getUrl) NSString* url;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(FHBRequestResultHandler*) __request;
+(FHBvirtualtour*) createWithXml:(DDXMLElement*)__node __request:(FHBRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(FHBRequestResultHandler*) __request;
@end